# Page settings
baseurl = "localhost:1313"
title = "ICONation"
languageCode = "en-us"
theme = "hugo-elate-theme"

[params]
  
  custom_css = ["css/custom1.css", "css/custom2.css"]

  # Meta
  author = "ICONation"
  description = "ICONation website"
  email = "iconation.team@gmail.com"

  # Navigation
  [params.navigation]
    brand = "ICONation"
    home = "Home"
    work = "Projects"
    services = "Services"
    about = "Our team"
    contact = "Contact"
 
  # Hero section
  [params.hero]
    title = "ICONation"
    subtitle = 'By ICONists, for ICONists.'

  # [params.intro.video]
  #   enable = false
  #   title = "Watch the video"
  #   icon = "icon-play2"
  #   url = "https://vimeo.com/channels/staffpicks/93951774"

  # Work section
  [params.work]
    enable = true
    title = "Projects"
    description = "Here are our contributions to the ICON ecosystem."
    # footertext = '** Demo images from <a href="http://plmd.me/" target="_blank">plmd.me</a>'

    [[params.work.row]]
      img = "icon-sdk-php.png"
      link = "https://github.com/iconation/icon-sdk-php"
      alt = "ICON SDK PHP"
      title = "ICON SDK PHP"
      subtitle = "Development SDK"

    [[params.work.row]]
      img = "icon-sdk-cpp.png"
      link = "https://github.com/iconation/icon-sdk-cpp"
      alt = "ICON SDK CPP"
      title = "ICON SDK CPP"
      subtitle = "Development SDK"

    [[params.work.row]]
      img = "aegis.png"
      link = "https://github.com/iconation/aegis"
      alt = "Aegis"
      title = "Aegis"
      subtitle = "ICON blockchain database & analyzer"

    [[params.work.row]]
      img = "citizen_node.png"
      link = "http://iconation.team:9100/api/v3/"
      alt = "ICONation Citizen Node"
      title = "ICONation Citizen Node"
      subtitle = "Fully synchronized Mainnet Node"

    [[params.work.row]]
      img = "teaser.png"
      alt = "And more!"
      title = "And more to come!"
      subtitle = "Soon 😉"

  # Services section
  [params.services]
    enable = true
    title = "Services"
    description = "[insert general ICONation purpose]"

    [[params.services.item]]
      title = "Secure"
      description = "[insert description about being a block producer here (security)]"
      icon = "icon-cube"

    [[params.services.item]]
      title = "Develop"
      description = "[insert description about development here (projects, contribution to ICON source code)]"
      icon = "icon-wrench"

    [[params.services.item]]
      title = "Nation"
      description = "[insert description about ICONists who vote for us (voting, social media)]"
      icon = "icon-flag"

      [[params.services.item]]
      title = "Educate"
      description = "[insert description about what we can teach to ICONists (articles, tutorials, ...)]"      
      icon = "icon-monitor"

  # About section
  [params.about]
    enable = true
    title = "Our team"
    description = ""

    [[params.about.item]]
      name = "Spl3en"
      # position = "Developer"
      description = "Spl3en has been actively assisting and supporting the ICON developer community on icondev.io, ICONDev Telegram, and other various ICON related developer channels as an administrator dating back to 2017. He has demonstrated an excellent understanding of the ICON blockchain by contributing directly to the official <a href='https://github.com/Spl3en?org=icon-project'>ICON project source code</a>. He has developed multiple tools for ICONists and is in the process of creating more. His main motivation is to bring more developers to the ICON ecosystem by providing useful tools, dApps and APIs through ICONation."
      img = "spl3en.png"
      alt = "Person1"
      social = [
        ["icon-twitter", "#"],
      ]

    [[params.about.item]]
      name = "Radio"
      # position = "Position"
      description = "Radio is a Senior Systems Analyst/Scrum Master for one of the largest IT providers in North America. Radio has been an active member of the ICON community since 2017 and currently serves as a community manager on various ICON Reddit, Telegram and Discord channels. In addition to being an ICONist and cryptocurrency enthusiast, Radio's interests include a wide variety of sports, music, and literature from around the world.  He is also a passionate advocate for global human and animal rights."
      img = "radio.png"
      alt = "Person2"
      social = [
        ["icon-twitter", "#"],
      ]

    [[params.about.item]]
      name = "Dimitris"
      # position = "Developer"
      description = "Dimitris is an ambitious software engineer, with over 4 years of professional experience in web application development & system administration. Some of his most notable achievements include the digital transformation of various volunteering organisations and having worked at the European Organisation for Nuclear Research (CERN) for 14 months as a software developer. During the last 1.5 years, he has also ventured into the field of blockchain and smart contract development. He has already made a Telegram bot prototype that alerts you on ICX balance changes and is now developing a PHP SDK for ICON."
      img = "dimitris.png"
      alt = "Person1"
      social = [
        ["icon-twitter", "#"],
      ]

    [[params.about.item]]
      name = "NorskKiwi"
      # position = "Position"
      description = "As well as his drive for growing innovative technology, NorskKiwi brings a diverse skillset to the ICONation team, crafted in part from 15 years of managerial experience in the hospitality and tourism industry. A unique blend of communication skills, prudent financial management, and creative flair balance out his more aspirational ambitions for ICON., NorskKiwi is passionate about cultural exchange and bringing people together from all walks of life. He wishes to see the ICON community lead the way forward towards the United Nations Sustainable Development Goals, particularly through increased democracy (especially via DID and blockchain voting), climate action, and poverty reduction. Originally from New Zealand, NorskKiwi has traversed the world and now calls Norway home."
      img = "norsk.png"
      alt = "Person4"
      social = [
        ["icon-twitter", "#"],
      ]

    [[params.about.item]]
      name = "CCClub"
      # position = "Position"
      description = "CCClub_17 is an investor, entrepreneur and has 15 years experience in the Legal Sector in Australia. CCClub_17 has been an active ICON community member and has served as an admin on several ICON community channels since 2017. Club’s passion is to see the expansion of the ICON ecosystem by building engaging dApps, inspiring ICONists through online marketing/promotional events, and delivering quality/transparent communications with fellow ICONists."
      img = "ccclub.png"
      alt = "ccclub"
      social = [
        ["icon-twitter", "#"],
      ]

  # Contact section
  [params.contact]
    enable = true
    map = false
    form = true
    title = "Get in touch"
    description = "You need to tell us something ? <br/>Contact us on our social media, or using the following form."
    
    # Available icons: http://simplelineicons.com/
    details = [
        # ["icon-home", "5555 Love Paradise 56 New Clity 5655, <br> Excel Tower United Kingdom"],
        # ["icon-phone", "(123) 465-6789"],
        ["icon-envelope", '<a href="mailto:iconation.team@gmail.com" target="_blank">iconation.team@gmail.com</a>'],
        ["icon-github", '<a href="https://github.com/ICONation" target="_blank">[GitHub] ICONation</a>'],
        ["icon-twitter", '<a href="https://twitter.com/ICONationTeam" target="_blank">[Twitter] @ICONationTeam</a>'],
        ["icon-medium", '<a href="https://medium.com/@iconation" target="_blank">[Medium] @ICONation</a>'],
        ["", '<span class="iconify" style="position:relative; left:-50px;" data-icon="ei:sc-telegram" data-inline="false"></span><a href="https://t.me/iconationteam" target="_blank" style="position:relative; left:-22px;">[Telegram] t.me/iconationteam</a>']
      ]

    name = "Name"
    email = "Email"
    # phone = "Phone"
    message = "Message"
    button = "Send message"

  # Footer section
  [params.footer]
    enable = true
    copyright = '&copy; ICONation. All Rights Reserved.'
    links = [
        # ["icon-github", "https://github.com/ICONation"],
        # ["icon-twitter", "https://twitter.com/ICONationTeam"],
        # ["icon-medium", "https://medium.com/@iconation"]
      ]
